{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.toolkits",
    "module": "EdToolKits",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EdToolKits-1.0.1.jar",
          "url": "EdToolKits-1.0.1.jar",
          "size": 88032,
          "sha512": "ce97d94ce90709a42a392535c072635ecb5edf786a88fdd8342f44ccb1b717c07663f4176d8271583eefa193a893c2d626b03601e4c3d3c040e6d65f07fa828b",
          "sha256": "7dde35afa7973bcd8bf574b2c9bcb5774343eb3c69de17c3dd036bf593faee2a",
          "sha1": "c9f5df3223ea792b892d1b2c80165ed450f4cc86",
          "md5": "3b0ffebf3656ec3c203d3e222cfb16f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "EdToolKits-1.0.1.jar",
          "url": "EdToolKits-1.0.1.jar",
          "size": 88032,
          "sha512": "ce97d94ce90709a42a392535c072635ecb5edf786a88fdd8342f44ccb1b717c07663f4176d8271583eefa193a893c2d626b03601e4c3d3c040e6d65f07fa828b",
          "sha256": "7dde35afa7973bcd8bf574b2c9bcb5774343eb3c69de17c3dd036bf593faee2a",
          "sha1": "c9f5df3223ea792b892d1b2c80165ed450f4cc86",
          "md5": "3b0ffebf3656ec3c203d3e222cfb16f9"
        }
      ]
    }
  ]
}
