{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.4.jar",
          "url": "Elib-1.0.4.jar",
          "size": 130987,
          "sha512": "5d12607b288e518c8077e5f6bdd3bf0fb389838113f0f5b29a2ddeaf1729ed861d465f19217db43e69f30b5aedac219b35251a90c9639b388e442ee223be47f8",
          "sha256": "6aab14a762c02b1b8b0858e51209592e662122273fcae4afa1577745a0fc7c26",
          "sha1": "9bd6f21825ddc085666c459cc71f3a91cc9f306a",
          "md5": "4ce1e769545fff7bde033a729f04c2f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.43.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "javase",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "Elib-1.0.4.jar",
          "url": "Elib-1.0.4.jar",
          "size": 130987,
          "sha512": "5d12607b288e518c8077e5f6bdd3bf0fb389838113f0f5b29a2ddeaf1729ed861d465f19217db43e69f30b5aedac219b35251a90c9639b388e442ee223be47f8",
          "sha256": "6aab14a762c02b1b8b0858e51209592e662122273fcae4afa1577745a0fc7c26",
          "sha1": "9bd6f21825ddc085666c459cc71f3a91cc9f306a",
          "md5": "4ce1e769545fff7bde033a729f04c2f4"
        }
      ]
    }
  ]
}
