{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.1-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.1-pre.jar",
          "url": "Elib-1.0.1-pre.jar",
          "size": 95127,
          "sha512": "a618d1be7ba0b30eae6f66a3eb70eb6824304dc12dc42646036cb7d57c9b19c596067879419953aef2c123be6ab3bc8c552dd4c67040c19f20a94a32092d47f3",
          "sha256": "10ca5b38144727fdae0fcb5b3097f7ab393022e68b9fbbcb29d9aec1629382a1",
          "sha1": "ac2d68558a8a76f88867701e143c43b3b7e3d702",
          "md5": "185aa72f94c411fe0b439e63a390d6c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Elib-1.0.1-pre.jar",
          "url": "Elib-1.0.1-pre.jar",
          "size": 95127,
          "sha512": "a618d1be7ba0b30eae6f66a3eb70eb6824304dc12dc42646036cb7d57c9b19c596067879419953aef2c123be6ab3bc8c552dd4c67040c19f20a94a32092d47f3",
          "sha256": "10ca5b38144727fdae0fcb5b3097f7ab393022e68b9fbbcb29d9aec1629382a1",
          "sha1": "ac2d68558a8a76f88867701e143c43b3b7e3d702",
          "md5": "185aa72f94c411fe0b439e63a390d6c5"
        }
      ]
    }
  ]
}
