{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.3.jar",
          "url": "Elib-1.0.3.jar",
          "size": 105302,
          "sha512": "faaaf26d7f1bb1c2ee75121fbf0466dfb80ab1373f43af7c2c4d015bd07f3cff40c2a26faff0824b26cb7fb44f378802a3d1f5858faa457f6dcd6f51fbf16970",
          "sha256": "efdd68465419839ebab072eeba4c62eb0532b2cc4424f051e66be1a15bc47357",
          "sha1": "11170d706d4b0c29e3281decdaad4b6c61371838",
          "md5": "2a74bd3ce9211d8c46967059b1420136"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Elib-1.0.3.jar",
          "url": "Elib-1.0.3.jar",
          "size": 105302,
          "sha512": "faaaf26d7f1bb1c2ee75121fbf0466dfb80ab1373f43af7c2c4d015bd07f3cff40c2a26faff0824b26cb7fb44f378802a3d1f5858faa457f6dcd6f51fbf16970",
          "sha256": "efdd68465419839ebab072eeba4c62eb0532b2cc4424f051e66be1a15bc47357",
          "sha1": "11170d706d4b0c29e3281decdaad4b6c61371838",
          "md5": "2a74bd3ce9211d8c46967059b1420136"
        }
      ]
    }
  ]
}
