{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.1.jar",
          "url": "Elib-1.0.1.jar",
          "size": 93671,
          "sha512": "a784d082e7addc06394e4d5065d9cd92f461c8857152f27cadee7c4ba3199045f2323b562bf2af9e6943e6c2f6f8d94d5a640521f0b0fe8f2c52a5f75c33ff14",
          "sha256": "dfbbcb832c4537ad54827afc568eed8f41ca4795a9cfd372ccf0ff1ff06044eb",
          "sha1": "723c838377be64dc663fcdf3c5094251c546a311",
          "md5": "107511b09278943cbf5eca0984d06ea0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Elib-1.0.1.jar",
          "url": "Elib-1.0.1.jar",
          "size": 93671,
          "sha512": "a784d082e7addc06394e4d5065d9cd92f461c8857152f27cadee7c4ba3199045f2323b562bf2af9e6943e6c2f6f8d94d5a640521f0b0fe8f2c52a5f75c33ff14",
          "sha256": "dfbbcb832c4537ad54827afc568eed8f41ca4795a9cfd372ccf0ff1ff06044eb",
          "sha1": "723c838377be64dc663fcdf3c5094251c546a311",
          "md5": "107511b09278943cbf5eca0984d06ea0"
        }
      ]
    }
  ]
}
