{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.1.jar",
          "url": "Elib-1.0.1.jar",
          "size": 92952,
          "sha512": "d91ddeed1546a9ac0f02fbb0e0b86b01172bae064208a2a885cb05cd0e1bc2522ed6f1ebae65069beedf03b95c81cfe9697850504f56cc2666c556facc184872",
          "sha256": "e7c1cc745fbac0bd7c653473b3e5bbd69ffdc4debee0913752d8f4cd31b52ed4",
          "sha1": "06ac9aeac1e4aa6fad74110f17bfddbb019f671c",
          "md5": "9d6b067ad33057a6f3978c226a1eab4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Elib-1.0.1.jar",
          "url": "Elib-1.0.1.jar",
          "size": 92952,
          "sha512": "d91ddeed1546a9ac0f02fbb0e0b86b01172bae064208a2a885cb05cd0e1bc2522ed6f1ebae65069beedf03b95c81cfe9697850504f56cc2666c556facc184872",
          "sha256": "e7c1cc745fbac0bd7c653473b3e5bbd69ffdc4debee0913752d8f4cd31b52ed4",
          "sha1": "06ac9aeac1e4aa6fad74110f17bfddbb019f671c",
          "md5": "9d6b067ad33057a6f3978c226a1eab4d"
        }
      ]
    }
  ]
}
