{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.1.jar",
          "url": "Elib-1.0.1.jar",
          "size": 92808,
          "sha512": "5cd0798cb572288aa03d9eff250c75a36fa11d3c593071860c0e8daba7f3c60a85d6e84c6b7e94a9ba729b530165898465c7632c4e00951b1a1e2f56660a62da",
          "sha256": "652cdd13c293e38c48007c3362db1f78408ad17a42688c0f59a2c3224f96c045",
          "sha1": "3a89ddb74bcd65c30fa505fca290f100382944f1",
          "md5": "3837fb91672a717b49f5b79d37a83f7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Elib-1.0.1.jar",
          "url": "Elib-1.0.1.jar",
          "size": 92808,
          "sha512": "5cd0798cb572288aa03d9eff250c75a36fa11d3c593071860c0e8daba7f3c60a85d6e84c6b7e94a9ba729b530165898465c7632c4e00951b1a1e2f56660a62da",
          "sha256": "652cdd13c293e38c48007c3362db1f78408ad17a42688c0f59a2c3224f96c045",
          "sha1": "3a89ddb74bcd65c30fa505fca290f100382944f1",
          "md5": "3837fb91672a717b49f5b79d37a83f7c"
        }
      ]
    }
  ]
}
