{
  "formatVersion": "1.1",
  "component": {
    "group": "top.ed333.elib",
    "module": "Elib",
    "version": "1.0.3_upgrade_to_commons_lang3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Elib-1.0.3_upgrade_to_commons_lang3.jar",
          "url": "Elib-1.0.3_upgrade_to_commons_lang3.jar",
          "size": 105302,
          "sha512": "92dc8c8189055b92431e02996d6c0cf637a1ba6e1df18f0c38284710daa97691d1479f01560d84652a31bb8cfa3f67e9babb9fb613d915c588123e79bf6b79b9",
          "sha256": "e80365b09c905230f023583318c71b72692e021174878b18728c61cf3eb3df76",
          "sha1": "f7093cc0440873855b25f245559f5fc1fa4a1b7f",
          "md5": "b122086542649b5fadc1ec81b67b5964"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.43.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "Elib-1.0.3_upgrade_to_commons_lang3.jar",
          "url": "Elib-1.0.3_upgrade_to_commons_lang3.jar",
          "size": 105302,
          "sha512": "92dc8c8189055b92431e02996d6c0cf637a1ba6e1df18f0c38284710daa97691d1479f01560d84652a31bb8cfa3f67e9babb9fb613d915c588123e79bf6b79b9",
          "sha256": "e80365b09c905230f023583318c71b72692e021174878b18728c61cf3eb3df76",
          "sha1": "f7093cc0440873855b25f245559f5fc1fa4a1b7f",
          "md5": "b122086542649b5fadc1ec81b67b5964"
        }
      ]
    }
  ]
}
